version: '3'
services:
  ros_gazebo:
    image: osrf/ros:humble-desktop-full
    container_name: ros2_humble
    network_mode: "host"
    privileged: true
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/osano/Documents/PICARX:/picarx
    working_dir: /picarx
    command: bash -c "source /opt/ros/humble/setup.bash && sleep infinity"
